const REQUEST_TIMEOUT = 1000 * 15;
const MSG_DELAY_TIME = 1000 * 2;
const URL_PREFIX = "/api";
const MAX_TAB_VIEW_COUNT = 10;

export {
    REQUEST_TIMEOUT,
    MSG_DELAY_TIME,
    URL_PREFIX,
    MAX_TAB_VIEW_COUNT
};